spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clinicdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:clinic_user}
    password: ${DB_PASSWORD:}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
