spring:
  application:
    name: ClinicBookPatientSyetem

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB         # TODO: update host/port/SID to match your instance
    driver-class-name: oracle.jdbc.OracleDriver
    username: ClinicSystem_db                                # TODO: your Oracle username
    password: 11223344                         # TODO: your Oracle password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false
