spring:
  application:
    name: ClinicBookPatientSyetem

  datasource:
    url: jdbc:h2:file:./data/clinicdb
    # TODO (Oracle): url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: org.h2.Driver
    # TODO (Oracle): driver-class-name: oracle.jdbc.OracleDriver
    username: sa
    # TODO (Oracle): username: clinic_user
    password:
    # TODO (Oracle): password: your_password_here

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    # TODO (Oracle): database-platform: org.hibernate.dialect.OracleDialect

  h2:
    console:
      enabled: true
      path: /h2-console
